# Generated by Django 4.1.2 on 2022-10-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0002_connects_users_to_bookmarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="created_by",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="modified_by",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
